<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<GenerateDocumentationFile>flase</GenerateDocumentationFile>
		<AssemblyTitle>Expander Backend</AssemblyTitle>
		<Company>Cream-CN</Company>
		<Product>Googology Expander</Product>
		<Copyright>Copyright © 2026 Cream-CN</Copyright>
		<Description>Expander 后端类库</Description>
		<AssemblyVersion>1.1.0.0</AssemblyVersion>
		<FileVersion>1.1.0.0</FileVersion>
		<InformationalVersion>1.0.0</InformationalVersion>
		<SatelliteResourceLanguages>en;zh-Hans</SatelliteResourceLanguages>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="Common\Sequence.fs" />
		<Compile Include="MrSSShare.fs" />
		<Compile Include="Core\Entry.fs" />
		<Compile Include="Core\EntryArena.fs" />
		<Compile Include="Notation\Omega-YMagma.fs" />
		<Compile Include="Notation\EpsilonY.fs" />
		<Compile Include="Notation\PrSS.fs" />
		<Compile Include="Notation\Empty.fs" />
		<Compile Include="MrSS121.fs" />
	</ItemGroup>

</Project>