<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<RootNamespace>Expander_CS</RootNamespace>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<AssemblyTitle>Expander</AssemblyTitle>
		<Company>Cream-CN</Company>
		<Product>Googology Expander</Product>
		<Copyright>Copyright © 2026 Cream-CN</Copyright>
		<Description>Expander MainProgram</Description>
		<AssemblyVersion>1.0.0.4</AssemblyVersion>
		<FileVersion>1.0.0.4</FileVersion>
		<InformationalVersion>1.0.0</InformationalVersion>
		<SatelliteResourceLanguages>en;zh-Hans</SatelliteResourceLanguages>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="Expander.Backend\Expander_CS.Backend.fsproj" />
	</ItemGroup>

</Project>